name = "Geometry"
uuid = "2a2127a6-0453-458d-9dd0-74020ca62f57"
authors = ["David Amaro Alcalá <dav1494@ciencias.unam.mx>"]
version = "0.1.0"

[deps]
RandomMatrices = "2576dda1-a324-5b11-aa66-c48ed7e3c618"
